module.exports = {
  'QUALITY_CONTROL': 'QUALITY_CONTROL',
  'DEVELOPMENT': 'DEVELOPMENT',
  'HUMAN_RESOURCE': 'HUMAN_RESOURCE',
  'RESEARCH_AND_DEVELOPMENT': 'RESEARCH_AND_DEVELOPMENT',
  'ACCOUNTING': 'ACCOUNTING'
};
